#!/bin/bash
###############################################
# Encrypt File Script                         #
#                                             #
# Usage: encrypt_file <file>                  #
#                                             #
# This script will encrypt a file with        #
# aes-256-cbc.                                #
#                                             #
# Written by: Todd Murphy                     #
###############################################

if [[ $# -ne 1 ]] ; then
    echo 'Usage: encrypt_file <file>'
    exit 0
fi

printf "Enter the name of the output file: "
read outputFile

filePath="$1"
DIR=$(dirname "${filePath}")

`openssl enc -aes-256-cbc -e -in "$1" -out "$DIR"/"$outputFile"`
